<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f4fffabf-4428-4c18-995e-cdeae0a172d9</elementGuidId>
    <imagePath></imagePath>
    <name>p_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[2]/div[3]/div[2]/div[1]/p[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>