<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c1b1db7-736b-42a4-bdf3-19b07b444f42</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[2]/div[1]/div[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>