<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d25ef3de-e8bc-46b6-a4db-e6de68ba9700</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[4]/div[1]/div[5]/div[1]/div[1]/div[3]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Show settings menu')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Show settings menu</value>
        <webElementGuid>050adadd-22a9-4068-bc8e-bd630e2c50f7</webElementGuid>
    </webElementProperties>
</WebElementEntity>