<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>35fe8ccd-27cf-4ed4-b08f-0556900c09d7</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_44</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/main[1]/div[2]/div[3]/div[2]/div[1]/ul[1]/li[3]/span[2]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>