<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e05743f-1536-40cd-8c79-84f1f0063d00</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_49</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]/div[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>